# provider - what to configure, aws, azure, gcp, etc - focus on azure with azurerm provider

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.55.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.5.1"
    }
  }
}

provider "azurerm" {
  # which data hall to work within
  subscription_id = "1abe8fed-e8e6-4365-afea-ed8ba68a94b8"
  features {}
}

locals {
  default_location = "norwayeast"
  default_tags     = {
    #<< support tags by policies (automatically generated by azure)
    Environment       = "prod"
    Team              = "citrix"
    "Technical Owner" = "suthakaran.kanesu@nav.no"
    Tenant            = "navno"
    #support
    demo              = "lærlinger(ene)"
    provenance        = "https://github.com/navikt/az-laerlinger-demo-tf"
    names             = "Lukasz, Herman"
  }
  no_of_rg = 3
}

## create random postfix
resource "random_string" "suffix" {
  count   = local.no_of_rg
  length  = 10
  special = false
  lower   = true
  upper   = false
  numeric = true
}

# create resource group

resource "azurerm_resource_group" "rg" {
  count    = local.no_of_rg
  name     = "demo-reg_${random_string.suffix[count.index].result}"
  location = local.default_location
  tags     = local.default_tags
}

#output "rg_id" {
#  value = azurerm_resource_group.rg.id
#}
#
#output "rg_name" {
#  value = azurerm_resource_group.rg.name
#}
